### ISSUE TITLE
Traduzir mensagens de erro

### ISSUE THREAD

**Issue by Jazancort** [eguatech/eguamat#15]

**Comment by Heictor** [comment]
Ao tentar declarar um vetor chamado "6a" ele apresenta esse erro.
![image](https://user-images.githubusercontent.com/39010251/80136475-244fca00-8578-11ea-8554-44d95fb721bc.png)

**Comment by BrennusCaio** [comment]
Foi feito um commit no dia 28 abril de 2020 resolvendo essa Issue.
