### ISSUE TITLE
Arrumar nome e descrição da documentação.

### ISSUE THREAD

**Issue by Jazancort** [eguatech/eguamat#35]
Arrumar o nome e descrição.
Ex: 
A função de velocidade média é descrita como "vmed(distância,tempo)". Oque dificulta o entendimento.
Então deve-se mudar o nome para "velocidade média" e na descrição colocar como usar a função.

**Comment by Heictor** [comment]
Realizei algumas alterações, e também inseri algumas ilustrações das funções gráficas assim como a ilustração das fórmulas utilizadas para realização dos cáculos. 

![image](https://user-images.githubusercontent.com/39010251/87225918-d4a6c080-c366-11ea-954f-5113c4c996dd.png)

![image](https://user-images.githubusercontent.com/39010251/87225943-f738d980-c366-11ea-8e25-a8112889fb7a.png)
