### ISSUE TITLE
Alteração de nome da pasta

### ISSUE THREAD

**Issue by lucaspompeun** [eguatech/eguamat#36]
Afim de evitar qualquer conflito na chamada dos arquivos javascript gostaria de solicitar a alteração do nome da pasta /js/matematica/funcao do 1 grau. Recomendo utilizar as padronizações do projeto com "funcao-1-gra" ou "funcao-primeiro-grau".

**Comment by Heictor** [comment]
Os arquivos foram reorganizados adequadamente.
